### ISSUE TITLE
漏词

### ISSUE THREAD

**Issue by Silencezjl** [tsroten/pynlpir#105]
`import pynlpir`
`pynlpir.open()`
`pynlpir.segment('儿童一岁生日蛋糕')`

The output is [('儿童', 'noun'), ('一', 'numeral'), ('岁', 'classifier'), ('生日', None)] , and it miss '蛋糕' in the output, this must be a bug!!!
输出居然把后面的“蛋糕”两个字吃了，模型喜欢吃蛋糕吗？

**Comment by zehuichen123** [comment]
There is something more when I run this funny code:  
```Python
>>> pynlpir.segment('儿童一岁生日蛋糕')
part of speech not recognized: 'gms'
[('儿童', 'noun'), ('一', 'numeral'), ('岁', 'classifier'), ('生日', None)]
```
It seems that `gms` is a key point to solve this problem :)

**Comment by Silencezjl** [comment]
yeah，I have the same waring. 
> part of speech not recognized: 'gms'

**Comment by tsroten** [comment]
@zehuichen123 @Silencezjl For the `gms` part of speech, see https://github.com/tsroten/pynlpir/issues/82

**Comment by tsroten** [comment]
@Silencezjl For "蛋糕", NLPIR sometimes does not do well without a punctuation mark. Try adding a period at the end:
```

>>> pynlpir.segment('儿童一岁生日蛋糕。')
part of speech not recognized: 'gms'
[('儿童', 'noun'), ('一', 'numeral'), ('岁', 'classifier'), ('生日蛋糕', None), ('。', 'punctuation mark')]
```
