### ISSUE TITLE
pynlpir 情感分析问题

### ISSUE THREAD

**Issue by pengshaowei** [tsroten/pynlpir#110]
打扰了，请问一下pynlpir里怎么实现情感分析，具体命令是什么？
参考网址如下:
https://github.com/NLPIR-team/NLPIR/tree/master/NLPIR%20SDK/SentimentAnalysis
http://ictclas.nlpir.org/nlpir/
http://ictclas.nlpir.org/nlpir/html/qinggan-5.html

**Comment by tsroten** [comment]
你好！ PyNLPIR没有情感分析，只有分词。

**Comment by tsroten** [comment]
https://github.com/tsroten/pynlpir/issues/39
