### ISSUE TITLE
nlpir导入用户字典

### ISSUE THREAD

**Issue by cavities** [tsroten/pynlpir#114]
data_csv = pd.DataFrame([[i['word'] +' ' +'n'] for i in list(term_dict)])
data_csv.to_csv('text_dict.csv',sep='\t',index=False,header=False,line_terminator='\n')
import pynlpir
from pynlpir import nlpir
pynlpir.nlpir.ImportUserDict('text_dict.csv')
-------------------------------------------------------
报错  ArgumentError: argument 1: <class 'TypeError'>: wrong type
那到底要什么样格式 才能通过

**Comment by tsroten** [comment]
`b'text_dict.csv'`

```
import pynlpir

data_csv = pd.DataFrame([[i['word'] +' ' +'n'] for i in list(term_dict)])
data_csv.to_csv('text_dict.csv',sep='\t',index=False,header=False,line_terminator='\n')
pynlpir.open()
pynlpir.nlpir.ImportUserDict(b'text_dict.csv')
```
