### ISSUE TITLE
[SOLVED] Again "RuntimeError: NLPIR function 'NLPIR_Init' failed."

### ISSUE THREAD

**Issue by bgerazov** [tsroten/pynlpir#116]
Everything was fine last time I used it, but today it gave me a `LicenseError` and I had to update using `pynlpir update` which said that the license was updated. The problem is that now it's not working. I get
```
 In [51]: pynlpir.open()
Traceback (most recent call last):

  File "<ipython-input-51-75c8c7051dce>", line 1, in <module>
    pynlpir.open()

  File "~/miniconda3/lib/python3.6/site-packages/pynlpir/__init__.py", line 108, in open
    raise RuntimeError("NLPIR function 'NLPIR_Init' failed.")

RuntimeError: NLPIR function 'NLPIR_Init' failed.
```
Can you help me?

Thanks!

**Comment by tsroten** [comment]
Hello @bgerazov! Typically when NLPIR fails to initialize it will log its errors to a file in its data directory.

In your case, you probably want to look for any `.err` or `.log` files in `~/miniconda3/lib/python3.6/site-packages/pynlpir/Data`. They are usually named with a date, like this: `20180926.err`.

Hopefully the content of those log files will help us figure out what's going on!

**Comment by bgerazov** [comment]
Hi @tsroten, thanks for your reply!

Indeed the err file reads:
``` [2018-09-26 13:56:28]	~/miniconda3/lib/python3.6/site-packages/pynlpir/Data/NLPIR.user Not valid license or your license expired! Please feel free to contact pipy_zhang@msn.com! ```

Ok - the problem was that I needed to re-import pynlpir for it to register the change ... 

Thanks for making pynlpir and keeping it up and running!
