### ISSUE TITLE
license问题，更新后仍然显示证书过期

### ISSUE THREAD

**Issue by pover-yang** [tsroten/pynlpir#122]
首先运行报错：
pynlpir.LicenseError: Your license appears to have expired. Try running "pynlpir update".
在正确环境下运行了 ：pynlpir update 同样不行
在GitHub上下载最新的 license 替换到正确文件目录下 同样不行

**Comment by wmchappy** [comment]
我的也是这样

**Comment by Weikoi** [comment]
我刚装完库第一次运行显示证书过期报错，在pycharm自带的terminal运行pynlpir update后，问题解决。
