### ISSUE TITLE
OSError: exception: access violation reading 0x000000000000000C

### ISSUE THREAD

**Issue by ArlanCooper** [tsroten/pynlpir#133]
调用如下命令:
s = '海洋是如何形成的'
segments = pynlpir.segment(s, pos_names='all')

报这样的错误:
OSError: exception: access violation reading 0x000000000000000C

**Comment by wangbyby** [comment]
代码最开始记得加上``pynlpir.open()``,
最后加上``pynlpir.close()``

**Comment by ArlanCooper** [comment]
> 代码最开始记得加上`pynlpir.open()`,
> 最后加上`pynlpir.close()`

好的，谢谢
