### ISSUE TITLE
Mac m1 issue

### ISSUE THREAD

**Issue by andreisavca** [tsroten/pynlpir#140]
Hi, can you compile libNLPIRios.so for Mac with M1 chip or share the source code?

**Comment by tsroten** [comment]
Hello! All of the binary files in this project come directly from the NLPIR project, so they'll need to build packages that are compatible with Apple Silicon: https://github.com/NLPIR-team/NLPIR/tree/master/NLPIR%20SDK/NLPIR-ICTCLAS
