### ISSUE TITLE
License Renewal

### ISSUE THREAD

**Issue by cidrugHug8** [tsroten/pynlpir#142]
What is the interval between license renewals?
Should it be done annually?

**Comment by tsroten** [comment]
I'm not 100% sure, but you can see how often the license file gets updated by the NLPIR team here: https://github.com/NLPIR-team/NLPIR/commits/master/License/license%20for%20a%20month/NLPIR-ICTCLAS分词系统授权

**Comment by cidrugHug8** [comment]
Thanks．
