### ISSUE TITLE
encode/decode error

### ISSUE THREAD

**Issue by fairsky66** [tsroten/pynlpir#22]
When I was trying to test this package with using the example you provide, I got error as following:
*UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: invalid continuation byte*

I was working with the package in both windows8 and Ubuntu 15 (but in a VM). Both gave me the same error.

**Comment by fairsky66** [comment]
@tsroten Hi, it seemed ok if I rewrote the code in pycharm. Though it did not work if I wrote it in sublime text and saving it in utf8 format. So, i think this is not nlpir relevant, but editor.

I will post any issue or incompatibility here if I found in future.

Cheers,

**Comment by tsroten** [comment]
@fairsky66 Okay, thanks for the update. Best of luck in your coding endeavors!

**Comment by jennywei1987** [comment]
Hi, I am newee, and I am using pynlpir to run some data.

I got the error...I am using eclipse, and python 2.7.

Below is my code:
> #coding=utf-8
>import pynlpir
>pynlpir.open()
>s = "美国第二届总统的名字是什么"
>print pynlpir.segment(s)
>pynlpir.close()

my result:
*[(u'\u7f8e\u56fd', u'noun'), (u'\u7b2c\u4e8c', u'numeral'), (u'\u5c4a', u'classifier'), (u'\u603b\u7edf', u'noun'), (u'\u7684', u'particle'), (u'\u540d\u5b57', u'noun'), (u'\u662f', u'verb'), (u'\u4ec0\u4e48', u'pronoun')]*

How would I modify the code?

Thanks a lot
