### ISSUE TITLE
Crash on key word generation

### ISSUE THREAD

**Issue by JTKBowers** [tsroten/pynlpir#23]
When the `get_key_words function` is called with weights enabled, certain sentences will cause errors.
OS: Ubuntu server 14.10, but the error is probably non os-specific.
```python
import pynlpir
pynlpir.open()
pynlpir.get_key_words('我们很好,你呢') #['我们']
pynlpir.get_key_words('我们很好,你呢', weighted=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pynlpir/__init__.py", line 220, in get_key_words
    word, pos, weight, count = w.split('/')
ValueError: need more than 3 values to unpack
```

**Comment by tsroten** [comment]
@JTKBowers Thanks for reporting this bug. It seems that NLPIR occasionally likes to mix up it's return value structure. Note the difference in the log messages between the two function calls:
```python
>>> pynlpir.get_key_words('我们都是美国人。', weighted=True)
DEBUG:pynlpir:Searching for up to 50 weighted key words in: 我们都是美国人。.
DEBUG:pynlpir:Finished key word search: 美国/nsf/0.01/1#.
DEBUG:pynlpir:Formatting key word search results.
DEBUG:pynlpir:Key words formatted: [('美国', 0.01)].
[('美国', 0.01)]
>>> pynlpir.get_key_words('我们很好,你呢', weighted=True)
DEBUG:pynlpir:Searching for up to 50 weighted key words in: 我们很好,你呢.
DEBUG:pynlpir:Finished key word search: 我们/rr/-1.00.
DEBUG:pynlpir:Formatting key word search results.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pynlpir/__init__.py", line 219, in get_key_words
    word, pos, weight, count = w.split('/')
ValueError: need more than 3 values to unpack
```

Normally NLPIR's `GetKeyWords` function returns key words like this:
```
美国/nsf/0.01/1
```
This tells us the word, part of speech, weight, and number of occurrences. However, with your sentence, the following is returned:
```
我们/rr/-1.00
```
So, not only is the weight negative, but there is no value that indicates the number of occurrences. The latter problem is what is causing the error message you're seeing.

I think this bug (which seems to be more on NLPIR's side) will force us to put an extra conditional in the PyNLPIR `get_key_words()` function to account for this problem.

I can't figure out why the weight is negative or why the word count is not included in the return. That would be helpful information to have, if anyone can figure it out. Either way, I'll commit a fix for this shortly.

**Comment by tsroten** [comment]
@JTKBowers This issue is now fixed in the `develop` branch.
