### ISSUE TITLE
I need the feature: New Word Indentification ,didn't find in API

### ISSUE THREAD

**Issue by jingjinjingjin** [tsroten/pynlpir#26]
I didn't find functions about New Word Indentification in the API page http://pynlpir.readthedocs.org/en/latest/api.html#pynlpir

In the NLPIR system, the functions are like 
NLPIR_NWI_Start();
NLPIR_NWI_AddFile(sInputFile); 
NLPIR_NWI_Complete();

How do I use these functions in python ?

**Comment by tsroten** [comment]
@jingjinjingjin Thanks for pointing this out. Looks like I overlooked adding those functions. I've added them in 059222d. I am working on the documentation for them now.

**Comment by tsroten** [comment]
Okay, this is now in the most recent version of PyNLPIR.

**Comment by jingjinjingjin** [comment]
Thank you, tsroten!
