### ISSUE TITLE
RuntimeError: NLPIR function 'NLPIR_Init' failed

### ISSUE THREAD

**Issue by GiterLI** [tsroten/pynlpir#28]
My python version is 2.7
PyNLPIR version is 0.2.2 and I uses "pip install pynlpir" to install it. 
OS is Ubuntu 12.04, 64bit
Thank you!

**Comment by tsroten** [comment]
@GiterLI Thanks for reporting this issue! NLPIR recently released a new version that isn't packaged with PyNLPIR yet. I will have an update out later today.

Thanks for using PyNLPIR!

Note: This was already reported in #25.

**Comment by GiterLI** [comment]
@tsroten  Yes, Thank you! I use 
$ git clone git://github.com/tsroten/pynlpir.git
$ pip install -e pynlpir
and the problem is solved. I think the pip install command has some problems.

**Comment by tsroten** [comment]
The latest version can now be installed via `pip`!

**Comment by CreamBing** [comment]
win64 python3.5.1 when I import pynlpir and run pynlpir.open()

**Comment by sajidnaeem** [comment]
hi brother i am unable to install it using pip.. 

Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\pip\_vendor\urllib3\response.py", line 302, in _error_catcher
    yield
  File "E:\anaconda\lib\site-packages\pip\_vendor\urllib3\response.py", line 384, in read
    data = self._fp.read(amt)

**Comment by tsroten** [comment]
@sajidnaeem Hello! I'm not able to see the actual error message and full trackback in your post. Can you try copying/pasting again? Thanks!

**Comment by sajidnaeem** [comment]
@tsroten  thanks brother i fixed it....
