### ISSUE TITLE
Is this the basic version or is there any advanced version?

### ISSUE THREAD

**Issue by GiterLI** [tsroten/pynlpir#29]
The performance is relative worse even than jieba. 
Here is an experiment:
The string is: s='我是歌手神截图上演宫心计 邓紫棋茜拉笔笔有杀气'
Here is the result of PyNLPIR:
我, 是, 歌手, 神, 截, 图, 上演, 宫, 心计,  , 邓紫棋, 茜, 拉, 笔, 笔, 有, 杀气

And here is the result of jieba:
我, 是, 歌手, 神, 截图, 上演, 宫, 心计,  , 邓紫棋茜, 拉, 笔笔, 有, 杀气

As we can see, PyNLPIR divides the combination " 截图".
Is there any advanced or payed version of NLPIR that can be used under Python?

**Comment by tsroten** [comment]
@GiterLI I'm sorry to hear you're having issues with NLPIR's segmentation results. PyNLPIR is simply a wrapper around [NLPIR/ICTCLAS](http://ictclas.nlpir.org/). It doesn't actually implement a segmentation algorithm itself. Essentially, that means I can't do anything about the segmentation results. For support and documentation about the actual segmentation process, you would have to check directly with NLPIR. They do have documentation that ships with [their releases](http://ictclas.nlpir.org/downloads). You could also try the [ICTCLAS forum](http://www.bigdatabbs.com/forum.php?mod=forumdisplay&fid=64).

I'm not sure if they have a paid or advanced version. PyNLPIR does support using a specific license code and custom `Data` directory. So, if you can get a license code or a fine-tuned `Data` directory, you *should* be able to use it with PyNLPIR.

**Comment by tsroten** [comment]
@GiterLI I'm going to go ahead and close this issue. If you need any other help, feel free to post again!
