### ISSUE TITLE
About the user dict 

### ISSUE THREAD

**Issue by taozhijiang** [tsroten/pynlpir#30]
Thanks for your work, help me quickly focus on my work with python and NLPIR.
All works well, but when I try with *user_dict*, problems occurs. Actually, I am not very familiar with python `ctypes`, so If you can offer a full example, really appreciate.

1. `nlpir.Init()` should take 3 arguments, the last `None` for *license* can not be missed.
2. I add my dict file under Dict directory, and `nlpir.ImportUserDict(dict_file)`, the content is 
    双卡双待 np

3.  ```python
    ss = bytes("我想要一个双卡双待的手机", encoding='utf-8')
    s = c_char_p(ss)
    size = ctypes.c_int()
    result = nlpir.ParagraphProcessA(s, ctypes.byref(size), True)
    print(repr(result))
    result_t_vector = ctypes.cast(result, ctypes.POINTER(nlpir.ResultT))
    words = []
    for i in range(0, size.value):
        r = result_t_vector[i]
        word = s[r.start:r.start+r.length]
        words.append((word, r.sPOS)) 
 
    print(words)

The code can not run...

Thanks and hope for your help.

**Comment by tsroten** [comment]
@taozhijiang Thanks for using PyNLPIR! Would you mind posting the error message that you get when you run your code?

**Comment by tsroten** [comment]
@taozhijiang It looks like your problem is this line: `s = c_char_p(ss)`. Here is a working version:
```python
import ctypes
import pynlpir
nlpir = pynlpir.nlpir

pynlpir.open()
nlpir.ImportUserDict(b'path/to/dict/file')  # Make sure you put the correct file in here.
s = bytes("我想要一个双卡双待的手机", encoding='utf-8')
size = ctypes.c_int()
result = nlpir.ParagraphProcessA(s, ctypes.byref(size), True)

result_t_vector = ctypes.cast(result, ctypes.POINTER(nlpir.ResultT))
words = []
for i in range(0, size.value):
    r = result_t_vector[i]
    word = s[r.start:r.start+r.length]
    words.append((word, r.sPOS)) 

for word, pos in words:
    print(word.decode('utf-8'), pos.decode('utf-8'))
```

That will output:
```python
我 rr
想 v
要 v
一个 mq
双卡双待 np
的 ude1
手机 n
```
Is that what you're looking for? I'll be sure to update the docs to include a better example.

**Comment by taozhijiang** [comment]
Thanks for your warm heart and quick reply, it works now through your way.
Thanks.
