### ISSUE TITLE
File permission errors on Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by waltbai** [tsroten/pynlpir#32]
```python
>>> import pynlpir
>>> pynlpir.open()
[2015-08-06 11:05:07] Cannot open file /usr/local/lib/python2.7/dist-packages/PyNLPIR-0.3.2-py2.7.egg/pynlpir/Data/NewWord.lst
Cannot write log file /usr/local/lib/python2.7/dist-packages/PyNLPIR-0.3.2-py2.7.egg/pynlpir/Data/20150806.err!
```

but seems it doesn't affect segment function...

**Comment by tsroten** [comment]
@waltbai Thanks for reporting these warning messages. These are messages that NLPIR outputs because it isn't able to read or write the file mentioned. I'm looking into another way to ship the NLPIR `Data` directory so that this won't happen.

**Comment by tsroten** [comment]
@waltbai Did you install PyNLPIR using `sudo`?

For example, did you run this: `sudo pip install pynlpir`

Or did you run this: `pip install pynlpir`?

**Comment by waltbai** [comment]
I use sudo pip to install the package.

**Comment by tsroten** [comment]
If you install PyNPIR using `sudo`, then you need to run Python using `sudo` as well. So, try `sudo python` and then import and open PyNLPIR. Does that get rid of the error?

**Comment by waltbai** [comment]
Yes, when I run python in sudo mode, the error does not occur. Thank you!
