### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by likegitcoding** [tsroten/pynlpir#34]
```bash
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    readme = open_file('README.rst')
  File "setup.py", line 21, in open_file
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 754: illegal
multibyte sequence
```

**Comment by tsroten** [comment]
@likegitcoding Thanks for reporting this. I'll explicitly declare the encoding to the `open()` function so it works on systems with other default encodings.

**Comment by jennywei1987** [comment]
Hi, I am newee, and I am using pynlpir to run some data.

I got the error...I am using eclipse, and python 2.7.

Below is my code:
># -*- encoding: UTF-8 -*-
>import pynlpir
>pynlpir.open()
>s = "美国第二届总统的名字是什么"
>print pynlpir.segment(s)
>pynlpir.close()

my result:
*[(u'\u7f8e\u56fd', u'noun'), (u'\u7b2c\u4e8c', u'numeral'), (u'\u5c4a', u'classifier'), (u'\u603b\u7edf', u'noun'), (u'\u7684', u'particle'), (u'\u540d\u5b57', u'noun'), (u'\u662f', u'verb'), (u'\u4ec0\u4e48', u'pronoun')]*

How would I modify the code?

Thanks a lot
