### ISSUE TITLE
Install fails on Windows 64-bit, Python 3

### ISSUE THREAD

**Issue by wangshunping** [tsroten/pynlpir#35]
![Uploading image.png…]()

Hello.

there is something wong when i install this package.

woule you mind help me fix it ?

system: window 64bit
python 3.4.1

error info:

OSERROR: [WinError126]

**Comment by wangshunping** [comment]
I have installed it through downlaod the zip file and 'python setup.py install '


So i close it .

**Comment by tsroten** [comment]
@wangshunping I'm glad you were able to fix the problem.

Another user has reported the same problem. Can you please post more information about the problem and how you fixed it?

**Comment by wangshunping** [comment]
LOL..

Just the most basic operator , install a python site-package.


download .tar file from https://github.com/tsroten/pynlpir

then 

```
cd /where/your/download/target.tar
tar xvf target.tar
cd target
sudo python3 setup.py install

```

Done~~

**Comment by muzier** [comment]
Thank u very much. I meet the same problem and finally I fix this problem by using wang's method. Thanks again~

**Comment by tsroten** [comment]
@wangshunping Thanks for explaining that!
