### ISSUE TITLE
Init Failed.

### ISSUE THREAD

**Issue by lomizandtyd** [tsroten/pynlpir#36]
I installed it by downloading the zip file.

pip install from the pypi lack of nlpir library.

It run right after that.

However, without any change, I got the message today:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lomiz/Downloads/pynlpir/pynlpir/__init__.py", line 99, in open
    raise RuntimeError("NLPIR function 'NLPIR_Init' failed.")
RuntimeError: NLPIR function 'NLPIR_Init' failed.

# And the output of data_dir, encoding_constant 
data_dir:/home/lomiz/Downloads/pynlpir/pynlpir
encoding_constant:1

```
There is no change in the source code.
And I check the directory, 
libraries here as they were.
```
>>> import os
>>> data_dir = '/home/lomiz/Downloads/pynlpir/pynlpir/' 
>>> os.listdir(data_dir + './lib/')
['NLPIR64.lib', 'NLPIR32.dll', 'NLPIR32.lib', 'libNLPIR32.so', 'NLPIR64.dll', 'libNLPIR64.so']
```
Is there any contraints in those libraries? Like time limits?

PS:
The result I got in 2.7.10, 3.4.3, 3.5.1 with clean install.

**Comment by tsroten** [comment]
@lomizandtyd Sadly, there isn't much we can do about this but wait until ICTCLAS/NLPIR fixes it. NLPIR's error message is:

``[...]pynlpir/pynlpir/Data/NLPIR.user Not valid license or your license expired! Please feel free to contact pipy_zhang@msn.com!```

Unfortunately, the latest version of NLPIR doesn't include a new license. So, we'll have to wait until a new version of NLPIR comes out.

**Comment by tsroten** [comment]
@lomizandtyd Ah, good news! It looks like the NLPIR team uploaded a new license. I've updated the repository. I'll release to PyPI later today.

**Comment by tsroten** [comment]
@lomizandtyd Okay, [PyNLPIR version 0.4 has been released](https://pypi.python.org/pypi/PyNLPIR).

**Comment by lomizandtyd** [comment]
@tsroten 
Thanks a lot for this news.

And you add those libraries!
