### ISSUE TITLE
RuntimeError: NLPIR function 'NLPIR_Init' failed.

### ISSUE THREAD

**Issue by lyjlyj517** [tsroten/pynlpir#38]
Help.I install the newest vertion 0.4,but still RuntimeError: NLPIR function 'NLPIR_Init' failed.
Environment: Windows-64bit + Python 2.7-32bit.
Any one have an idea?

**Comment by tsroten** [comment]
@lyjlyj517 Can you please provide the entire error message and stack trace please? That will help us figure out what the problem might be.

**Comment by lyjlyj517** [comment]
@tsroten I heard that a new version was published by the raw developer recently.So I changed the NLPIR.user file in the Data folder manually,and it works ! Sorry for forgetting to save the entire stack trace,but I think this should be where the problem lies.

**Comment by zyshin** [comment]
```
>>> pynlpir.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Coding\Python\virtualenv\env\lib\site-packages\pynlpir\__init__.py", line 97, in open
    raise RuntimeError("NLPIR function 'NLPIR_Init' failed.")
RuntimeError: NLPIR function 'NLPIR_Init' failed.
```

Got the same issue. I downloaded the [latest NLPIR package](http://ictclas.nlpir.org/) and replaced the contents in the `Data` folder and the corresponding binaries in the `Lib` folder and finally it worded. I suggest the NLPIR modue packaged in pynlpir get updated.

**Comment by tsroten** [comment]
@zyshin @lyjlyj517 Thanks for the information. I've updated the license file in the repository. I'll release a PyPI version shortly.

**Comment by tsroten** [comment]
Okay, PyNLPIR v0.4.1 has been published to PyPI. You can now download it via `pip`.
