### ISSUE TITLE
Premature exit when dealing with a large file

### ISSUE THREAD

**Issue by zmlarry** [tsroten/pynlpir#40]
I'm trying to segment a somewhat large file (~700MB), but the program exits prematurely after processing about 20% of the file, without any error message.
Here's the script I use:
`cat input.zh | sudo python3 tokenizeAndPOS-zh-pynlpir.py > output.zh`
And my program `tokenizeAndPOS-zh-pynlpir.py` is as simple as this:

    import sys
    import pynlpir
    pynlpir.open(encoding_errors='ignore')
    for line in sys.stdin:
            line = line.strip()
            words = pynlpir.segment(line, pos_names=None)
            print(' '.join(word for word, flag in words))
    pynlpir.close()

I even tried locating the line where the program stopped, and feeding in the lines around, then the program worked fine. It appears that the problem is not caused by special character sequences.

**Comment by tsroten** [comment]
@zmlarry Thanks for using PyNLPIR!

You say the program "exits prematurely". Do you mean that it stops printing output and returns you to the command prompt?

Have you had this problem with other files?

If you'd be willing to upload the file or email it to me, I'd be happy to take a look at it.

**Comment by zmlarry** [comment]
@tsroten Thank you for your reply!

Yes, that's what I mean by "premature exit".

I realized I should flush the output before locating the line where the program stopped. It turned out that the problem has nothing to do with file size. The line below suffices to trigger the problem:
`Radio Kaleidoscope eye's`
If you can't reproduce the problem, it may be because some special characters are lost from copy and paste. In that case, I can email the file excerpt that contains this line.

**Comment by tsroten** [comment]
@zmlarry That line is working for me. Why don't you try emailing me an excerpt of the file?

Also, you could try setting the `encoding_errors` keyword to `replace` or `strict`, e.g. `pynlpir.open(encoding_errors='ignore')`. If you set it to `replace`, it might help NLPIR process that sentence. If you set it to `strict`, it could possibly help you track down which character is causing an error.

**Comment by tsroten** [comment]
@zmlarry Changing `encoding_errors` to `strict` revealed the error:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    words = pynlpir.segment(line, pos_names=None)
  File "/Users/troten/.virtualenvs/tmp-32aa86833f175e9/lib/python3.5/site-packages/pynlpir/__init__.py", line 194, in segment
    result = _decode(result)
  File "/Users/troten/.virtualenvs/tmp-32aa86833f175e9/lib/python3.5/site-packages/pynlpir/__init__.py", line 121, in _decode
    return s if isinstance(s, unicode) else s.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 33: invalid start byte
```

There is a non-utf-8 byte sequence on that line. You can fix it by either correcting the line (retype it manually in your file) or by setting `encoding_errors` to `replace`.

**Comment by zmlarry** [comment]
@tsroten Thank you! I thought `ignore` would suppress this kind of error; now I see `replace` should be used instead.

**Comment by zmlarry** [comment]
@tsroten Well, it turned out that `replace` didn't work; the program still broke like `ignore`. I ended up removing each line that is problematic.

**Comment by tsroten** [comment]
Yeah, NLPIR is pretty sensitive as far as it's expected input goes. The `'replace'` and `'ignore'` options help sometimes, but not always. Glad it's working for you now.
