### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by fighting41love** [tsroten/pynlpir#42]
RuntimeError: NLPIR function 'NLPIR_Init' failed.

They released a new version on Janurary 29 2016.
The previous license is invalid.
I tried to update the license file, but failed to make it work.
Will you update the pynlpir these days ?

Thanks!

Best regards,
YY

**Comment by yksk** [comment]
Got the same issue.
I install the newest vertion 0.4.1,but still RuntimeError: NLPIR function 'NLPIR_Init' failed.
Environment: Windows-64bit + Python 2.7-32bit.

>>> pynlpir.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxxxxx\AppData\Local\Continuum\Anaconda\lib\site-packages\pynlpir-0.4.1-py2.7.egg\pynlpir\__init__.py", line 97, in open
    raise RuntimeError("NLPIR function 'NLPIR_Init' failed.")
RuntimeError: NLPIR function 'NLPIR_Init' failed.

Please help....

**Comment by tsroten** [comment]
@fighting41love @yksk Thanks for letting me know a new license is out. I've released a new version of PyNLPIR (0.4.2). You can download it via `pip`.

https://pypi.python.org/pypi/PyNLPIR
