### ISSUE TITLE
pynlpir.open RuntimeError

### ISSUE THREAD

**Issue by anoidgit** [tsroten/pynlpir#50]
I install the package by pip install pynlpir, It reports pynlpir\__init__.py line97.in open
raise RuntimeError("NLPIR function 'NLPRI_Init' failed.")
I installed 32-bit python 2.7.11 on 64-bit Windows 10.
Is there anything I could do to fix this?thanks for help.

**Comment by anoidgit** [comment]
I fix it by replace folder Data from official package

**Comment by tsroten** [comment]
@anoidgit Thanks for pointing this out. This has been fixed.

**Comment by anoidgit** [comment]
my pleasure
