### ISSUE TITLE
nlpir.AddUserWord maybe wrong

### ISSUE THREAD

**Issue by pkwv** [tsroten/pynlpir#51]
I use nlpir.AddUserWord to add "北京师范大学" to the dictionary, the return value is **2**
But when I call nlpir.ParagraphProcessA("北京师范大学",ctypes.byref(size),True)
The result is only "北京" without the last four characters.

**Comment by tsroten** [comment]
@pkwv It looks like our license was out-of-date. I've updated PyNLPIR. Can you update your version to v0.4.4 and try again? You can download it straight from PyPI at https://pypi.python.org/pypi/PyNLPIR

Or, if you use pip you can try this:
```bash
pip install --upgrade pynlpir
```

**Comment by pkwv** [comment]
@tsroten It works after upgrade
thank you
