### ISSUE TITLE
when my user dict is too big, it does not work

### ISSUE THREAD

**Issue by wabyking** [tsroten/pynlpir#56]
Traceback (most recent call last):
  File "****.py", line 20, in <module>
    pynlpir.nlpir.ImportUserDict("user.dict")
WindowsError: exception: access violation reading 0x0000000000000001

**Comment by tsroten** [comment]
@wabyking I'm sorry it's taken me so long to get back to you. The error seems to suggest there is a problem reading the file. `access violation` -- are you sure the file has the correct permissions?
