### ISSUE TITLE
NLPIR function 'NLPIR_Init' failed,icense is out 

### ISSUE THREAD

**Issue by stud20090001** [tsroten/pynlpir#57]
import pynlpir
pynlpir.open()
RuntimeError: NLPIR function 'NLPIR_Init' failed.

err log:
[2016-07-01 09:47:08]   d:\Anaconda3\lib\site-packages\pynlpir\Data\NLPIR.user Not valid license or your license expired! Please feel free to contact pipy_zhang@msn.com!

**Comment by LucaDemo** [comment]
Same here, probably it's the same problem that there has been on Aug 1st 2015: https://github.com/tsroten/pynlpir/issues/31

**Comment by RangoHU** [comment]
Same here.

**Comment by NickPoon** [comment]
Same here.  The problem seems can be solved as in [#38](https://github.com/tsroten/pynlpir/issues/38)

**Comment by JingwenJessica** [comment]
Same here. I update the user license file and everything works now.

Downloaded the [latest NLPIR package(2016-06-07)](http://ictclas.nlpir.org/newsdownloads?DocId=389) and replaced the NLPIR.user file in the Data folder. This should save the problem.

**Comment by LucaDemo** [comment]
Yep it works, thanks

**Comment by haoran-zhang** [comment]
They expire the license very often. You can check the date+'.err' file in Data, most of the reason is the license was expired. You can folk their github account, download and replace the license in Data at the first time.  https://github.com/NLPIR-team/NLPIR/tree/master/License

**Comment by tsroten** [comment]
I've updated the license file in version 0.4.5 of PyNLPIR.

**Comment by tsroten** [comment]
Also, I've been working on a license auto-updater. I'd appreciate any help with testing it on Windows. For anyone who wants to help and knows how to run PyNLPIR from the `develop` branch, could you give it a shot? After it's installed, `pynlpir update` is the command that can be run to update the license.

**Comment by tsroten** [comment]
Okay, the license auto-updater has been successfully tested on Windows (and Linux and OS X). The notable downside is that NLPIR now packages their licenses in RAR archives, so any system that runs PyNLPIR's license downloader/updater will need to have some type of software that can extract RAR archives.

On OS X -- it's trivial:
```
brew install unrar
```

On Linux, it's also trivial:
```
sudo apt-get install 7zip-rar
```

On Windows, it's almost trivial:
- You have to download UnRAR for Windows
- You have to put it somewhere on your `%PATH%`

**Comment by tsroten** [comment]
The trouble is, since February 2016, NLPIR has released the NLPIR-ICTCLAS license in three different formats.

First, [in February](https://github.com/NLPIR-team/NLPIR/blob/487eec3041772a8aa30f24fddc1a7a42c80eebb8/License/license%20for%20a%20month/NLPIR-ICTCLAS%E5%88%86%E8%AF%8D%E7%B3%BB%E7%BB%9F%E6%8E%88%E6%9D%83/NLPIR.user) it was the binary `.user` license file.
Second, [a week ago](https://github.com/NLPIR-team/NLPIR/blob/b4adf146005a1f8b8d461293a26b3a467b74e01c/License/license%20for%20a%20month/NLPIR-ICTCLAS%E5%88%86%E8%AF%8D%E7%B3%BB%E7%BB%9F%E6%8E%88%E6%9D%83.zip) it was published as a ZIP archive.
Third, [six days ago](https://github.com/NLPIR-team/NLPIR/commit/5f4e9e7b676a4753c39d514e58de9e686620cc71) it was changed to a RAR archive.

So, we don't have any assurances that an auto-updater will continue working. If this doesn't work, obtaining the license file might have to be made manual. And then, PyNLPIR will just have a convenience CLI to add the license to the appropriate directory.

**Comment by tsroten** [comment]
I've reached out to Dr. Zhang to see if he will consider standardizing the format he uploads the new license files in.

**Comment by soledada** [comment]
The problem occurs in the first day of 2017
So is there some error about the auto-updater ?

I replace the "NLPIR.user" on my computer with this file:
https://github.com/NLPIR-team/NLPIR/blob/master/License/license%20for%20a%20month/NLPIR-ICTCLAS%E5%88%86%E8%AF%8D%E6%8E%88%E6%9D%83/NLPIR.user
And it seems pynlpir works now.

**Comment by rafael75012** [comment]
@soledada 
Thanks for your intervention.
I have the same problem, that I actually try to solve
When I click on your link, I get "Page not Found"

**Comment by tsroten** [comment]
Ok, the license updater is in version 0.5: https://pypi.python.org/pypi/PyNLPIR

`pynlpir update` to install/update the license.

**Comment by hanhan4321** [comment]
I use pynlpir update to update the license,it also has the the same error:
 pynlpir.LicenseError: Your license appears to have expired. Try running "pynlpir update".
then I debug it ,find it in __init.py__
 
elif 'Can not open License file' in line:
                        raise LicenseError('Your license appears to be '
                                           'missing. Try running "pynlpir '
                                           'update".') 

I tried many times,I don't know the reason.

**Comment by tsroten** [comment]
Hi @hanhan4321! Can you please tell me what it says when you run `pynlpir update` from your terminal?

**Comment by hanhan4321** [comment]
Today, it's ok. The NLPIR-team updates the April license today.  Thank you！

**Comment by cidrugHug8** [comment]
I tried to update pynlpir and failed.  The error is described below:

> Traceback (most recent call last):
  File "/usr/local/bin/pynlpir", line 9, in <module>
    load_entry_point('PyNLPIR==0.5.2', 'console_scripts', 'pynlpir')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2280, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1990, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.2/dist-packages/PyNLPIR-0.5.2-py3.2.egg/pynlpir/cli.py", line 14, in <module>
    import click
  File "/usr/local/lib/python3.2/dist-packages/click-6.7-py3.2.egg/click/__init__.py", line 18, in <module>
    from .core import Context, BaseCommand, Command, MultiCommand, Group, \
  File "/usr/local/lib/python3.2/dist-packages/click-6.7-py3.2.egg/click/core.py", line 8, in <module>
    from .types import convert_type, IntRange, BOOL
  File "/usr/local/lib/python3.2/dist-packages/click-6.7-py3.2.egg/click/types.py", line 6, in <module>
    from .exceptions import BadParameter
  File "/usr/local/lib/python3.2/dist-packages/click-6.7-py3.2.egg/click/exceptions.py", line 2, in <module>
    from .utils import echo
  File "/usr/local/lib/python3.2/dist-packages/click-6.7-py3.2.egg/click/utils.py", line 224
    message = message or u''
                           ^
SyntaxError: invalid syntax

Could you give me some advice?

**Comment by getmr** [comment]
In [12]: pynlpir.nlpir.ImportUserDict("/Users/zhangjintao/Desktop/随笔/中文分词比较/httpcws_dict.txt")
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-12-c1d93aa332c2> in <module>()
----> 1 pynlpir.nlpir.ImportUserDict("/Users/zhangjintao/Desktop/随笔/中文分词比较/httpcws_dict.txt")

ArgumentError: argument 1: <class 'TypeError'>: wrong type
