### ISSUE TITLE
mac install err

### ISSUE THREAD

**Issue by ljdawn** [tsroten/pynlpir#58]
Hi. I'm trying to install this package on mac, but get error .Bellow is the msg. thank you .
`Installed /Users/itjuzi/env/lib/python2.7/site-packages/PyNLPIR-0.4.5-py2.7.egg
Processing dependencies for PyNLPIR==0.4.5
Searching for patool
Reading https://pypi.python.org/simple/patool/
Best match: patool 1.12
Downloading https://pypi.python.org/packages/1b/eb/ad3c94cb8cbc1d8b1c47471d2c43537a05fda2bdff54a7d8248873591691/patool-1.12.tar.gz#md5=32a764139a018c6bc497b25630513a33
Processing patool-1.12.tar.gz
Writing /tmp/easy_install-qsp8Mo/patool-1.12/setup.cfg
Running patool-1.12/setup.py -q bdist_egg --dist-dir /tmp/easy_install-qsp8Mo/patool-1.12/egg-dist-tmp-RcUleC
error: Setup script exited with error: SandboxViolation: open('/Users/itjuzi/env/lib/python2.7/site-packages/_patool_configdata.py', 'w') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.`

**Comment by tsroten** [comment]
@ljdawn It looks like you're installing the development version. I'm still working out some kinks there. I'd recommend installing the latest official version via:

`pip install pynlpir`

Or, if you're installing from source:
```bash
cd pynlpir
git checkout master
python setup.py install
```

**Comment by ljdawn** [comment]
@tsroten  I'm installing that from source.  Thank you . That works fine
