### ISSUE TITLE
pynlpir.open failed with runtime error

### ISSUE THREAD

**Issue by fengxia41103** [tsroten/pynlpir#59]
`raise RuntimeError("NLPIR function 'NLPIR_Init' failed.")`

Was working until we did `pip install --upgrade pynlpir` to ugrade to 0.4.5. Rolled back to 0.4.3 complained about license out of date.

**Comment by tsroten** [comment]
@fengxia41103 Can you please paste the entire traceback and error message?

**Comment by tsroten** [comment]
@fengxia41103 The license is out-of-date again. I've just updated PyNLPIR again. Try again with the latest version via `pip install --upgrade pynlpir`
