### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by xxx0624** [tsroten/pynlpir#61]
when sentence = ‘申报’， there would throw TypeError.
![image](https://cloud.githubusercontent.com/assets/5348141/18834115/c9c8286c-8426-11e6-84a8-1ce4ea55efec.png)
this is my code:
![image](https://cloud.githubusercontent.com/assets/5348141/18834153/efac649e-8426-11e6-9c2a-3ccacd2acadb.png)

**Comment by tsroten** [comment]
PyNLPIR has since been updated. Try to upgrade and give this a try again. Thanks!
