### ISSUE TITLE
TypeError on 64bit win7

### ISSUE THREAD

**Issue by LiuHuaYi** [tsroten/pynlpir#63]
when i import pynlpir, i get an error,TypeError: LoadLibrary() argument 1 must be string, not unicode

**Comment by anoidgit** [comment]
The same problem has happened to me on win10 x64, after I update python 2.7.13

**Comment by anoidgit** [comment]
I replace "libNLPIR = cdll.LoadLibrary(lib)" with "libNLPIR = cdll.LoadLibrary(lib.encode("utf-8"))" in pynlpir/nlpir.py and fix this. @LiuHuaYi

**Comment by tsroten** [comment]
This is fixed and can be installed via pip: `pip install --upgrade pynlpir`

Thanks!

**Comment by anoidgit** [comment]
My pleasure. @tsroten

**Comment by jadestrong** [comment]
if `replace "libNLPIR = cdll.LoadLibrary(lib)" with "libNLPIR = cdll.LoadLibrary(lib.encode("utf-8"))"` will throw an error `typeerror-bad-argument-type-for-built-in-operation` on python 3.5  64bit win10, I reset it, it  
works

**Comment by tsroten** [comment]
@jadestrong So, it seems like it's a difference between Python 2 and Python 3 on Windows. Thanks for mentioning this.

This is not clearly indicated in Python's documentation, so we're kind of relying on trial and error here.

I'll try to get a Windows machine up and running to test this in the various Python versions.

**Comment by tsroten** [comment]
@jadestrong This should be fixed. If you could, please test it and let me know.

Run `pip install --upgrade pynlpir` to upgrade PyNLPIR.

**Comment by jadestrong** [comment]
@tsroten I've tested it.  there is no problem
