### ISSUE TITLE
Pynlpir Accuracy

### ISSUE THREAD

**Issue by rafael75012** [tsroten/pynlpir#64]
Hi, 

I am a user of Pynlpir, and I would like to know where I can found the results of its accuracy tests, if any have been processed.

**Comment by tsroten** [comment]
Hi! Thanks for using PyNLPIR!

PyNLPIR doesn't do any language processing itself. It is a wrapper around NLPIR, which is a separate project. You can find more information about that project [here](http://ictclas.nlpir.org). It is featured in academic journal articles and various online sources.

**Comment by rafael75012** [comment]
Thank you for your very quick response.
But ICTCLAS seems to have been updated many, I know for example ICTCLAS2008 and ICTCLAS 2014. On which version is Pynlpir based?

**Comment by tsroten** [comment]
The 2015 version.

**Comment by rafael75012** [comment]
Thank you so much
