### ISSUE TITLE
PyNLPIR/ICTCLAS Segmentation Tool

### ISSUE THREAD

**Issue by rafael75012** [tsroten/pynlpir#65]
I know PyNLPIR is ICTCLAS wrapper, but I don't manage to find neither to get any confirmation about on which corpora has been trained ICTCLAS. In (Zhang, 2002) it is explained it was PKU at this time, but I don't manage to know if its still the case for ICTCLAS2015.
Thanks so much if you could provide me any information.

**Comment by tsroten** [comment]
I would try reaching out to Dr. Kevin Zhang directly. I've communicated with him in the past and found him to be responsive. You can find his contact information on the [NLPIR GitHub repo](https://github.com/NLPIR-team/NLPIR).

**Comment by rafael75012** [comment]
Thanks,

He responded me that the corpus is one month of the People's Daily.
