### ISSUE TITLE
TypeError: this function takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by ucaszx** [tsroten/pynlpir#70]
hey, I tried to use pynlpir.nlpir.ParagraphProcess , and  I got this

    s = nlpir.ParagraphProcess(query, pos_tagging=False)
TypeError: this function takes at least 2 arguments (1 given)

it seems that only 1 argument is passed into the C++ function

**Comment by tsroten** [comment]
@ucaszx I think the issue is that the documentation makes it look like `pos_tagging` is a named argument. Try this instead:
```python
s = nlpir.ParagraphProcess(query, False)
```

**Comment by ucaszx** [comment]
tks, it works
