### ISSUE TITLE
nlpir.GetNewWords doesn't work

### ISSUE THREAD

**Issue by HGYD** [tsroten/pynlpir#74]
Hi, 
I try the GetNewWords API. However it returns emtry str result.
~~~~
import pynlpir
from pynlpir import nlpir

pynlpir.open()
nlpir.Init(nlpir.PACKAGE_DIR, nlpir.UTF8_CODE,'')
a="我们也可以在MacBook, iPhone使用我们实验室包括分词在内的各类大数据搜索与挖掘工具了"
word = nlpir.GetNewWords(a, 1, False)
print word
~~~~~

return: 
emtry  str

**Comment by tsroten** [comment]
@HGYD It appears that starting in 2016, NLPIR is no longer used for new word finding:

>> 注:从 2016 版本开始，该功能独立为关键词抽取组件，对应函数为: NWF_GetNewWords,
请访问: https://github.com/NLPIR-team/NLPIR/tree/master/NLPIR%20SDK/NewWordFinder
