### ISSUE TITLE
I want to know if I can use the find new word mode to seperate the word.

### ISSUE THREAD

**Issue by Matt233** [tsroten/pynlpir#76]
when I use a paragraph to test ,I found that the words found by pynlpir.nlpir.GetNewWords() can't be seperated by pynlpir.segment().SoI want to know if I can use the find new word mode to seperate the word.thanks.

**Comment by tsroten** [comment]
@Matt233 I think you need to add the new words to the dictionary before you segment ([`pynlpir.nlpir.AddUserWord`](http://pynlpir.readthedocs.io/en/latest/api.html#pynlpir.nlpir.AddUserWord)).
