### ISSUE TITLE
“segmention fault”

### ISSUE THREAD

**Issue by lampda** [tsroten/pynlpir#79]
for example
>>> import pynlpir as pp
>>> pp.segment(u'我有一个苹果')
[1]    10797 segmentation fault  python

can you help or advise? Thanks.

**Comment by tsroten** [comment]
Hi @lampda! Check out our readme or documentation. You have to open NLPIR, first:

```python
import pynlpir as pp
pp.open()
pp.segment(u'我有一个苹果')
```

**Comment by lampda** [comment]
Oh, that is.
Cheers.
