### ISSUE TITLE
Not valid license or your license expired!!!

### ISSUE THREAD

**Issue by 363325971** [tsroten/pynlpir#80]
2017-06-22 15:54:59] /usr/local/lib/python2.7/site-packages/pynlpir/Data/NLPIR.user Not valid license or your license expired! Please feel free to contact pipy_zhang@msn.com! 

How to solve this?

**Comment by 363325971** [comment]
>>> print(pynlpir.__version__)
0.5.2

**Comment by tsroten** [comment]
@363325971 Try running this in your terminal:
```bash
$ pynlpir update
```

**Comment by 363325971** [comment]
@tsroten 
>>> import pynlpir
>>> pynlpir.open()
[2017-06-23 10:11:17] Cannot open file /usr/local/lib/python2.7/site-packages/pynlpir/Data/NewWord.lst
Cannot write log file /usr/local/lib/python2.7/site-packages/pynlpir/Data/20170623.err!
>>> pynlpir.segment('我们都是好朋友')
[(u'\u6211\u4eec', u'pronoun'), (u'\u90fd', u'adverb'), (u'\u662f', u'verb'), (u'\u597d', u'adjective'), (u'\u670b\u53cb', u'noun')]

This is what I got from a segment, seems the result displays in unicode form

**Comment by tsroten** [comment]
Yes, PyNLPIR returns Unicode, not bytes. You can print each Unicode string in the output to see it in the interpreter. Or you can call encode on the Unicode strings to encode them using your preferred encoding.
