### ISSUE TITLE
Partial word returned from NLPIR ParagraphProcess

### ISSUE THREAD

**Issue by githwd2016** [tsroten/pynlpir#81]
I want use pynlpir for word segmentation, but somthing wrong happen:
My code:
    pynlpir.open()
    a = '中国新闻网'
    seg = pynlpir.segment(a, pos_tagging=False)
    print(seg)
    pynlpir.close()
The result:
    ['中国']
It seems that the word '新闻网' is gone.

**Comment by githwd2016** [comment]
My operate system is Ubuntu 16.04, and the version of pynlpir is 0.5.2

**Comment by tsroten** [comment]
@githwd2016 The NLPIR library appears to only be returning one word. It appears to work if you add a period at the end. I'm not sure why that is. You'd have to ask the NLPIR team about that.

```python
>>> import pynlpir
>>> pynlpir.open()
>>> a = '中国新闻网。'
>>> print(pynlpir.segment(a, pos_tagging=False))
['中国新闻网', '。']
```

**Comment by githwd2016** [comment]
@tsroten Thanks. After add a period, it seems working normally.
