### ISSUE TITLE
pynlpir.open()报错

### ISSUE THREAD

**Issue by Yif18** [tsroten/pynlpir#84]
import pynlpir
pynlpir.open()

F:\Anaconda2\python.exe F:/PycharmProjects/yif001/pynlpir.py
Traceback (most recent call last):
  File "F:/PycharmProjects/yif001/pynlpir.py", line 2, in <module>
    import pynlpir
  File "F:\PycharmProjects\yif001\pynlpir.py", line 3, in <module>
    pynlpir.open()
AttributeError: 'module' object has no attribute 'open'

**Comment by tsroten** [comment]
I'm not familiar with Anaconda. Can you check if pynlpir is actually being imported as a module and what version it is?
```python
import pynlpir
print(pynlpir.__version__)
print(dir(pynlpir))
```

**Comment by lomizandtyd** [comment]
This problem is caused by the name of your python script.

Rename your script, do not use 'pynlpir.py'.

python would load your file before load the pynlpir library.

**Comment by tsroten** [comment]
@lomizandtyd Nice job noticing that 😄
