### ISSUE TITLE
python3.6 pynlpir.nlpir.ImportUserDict ctypes.ArgumentError

### ISSUE THREAD

**Issue by jianghc724** [tsroten/pynlpir#90]
Hi, tsroten!
I have encountered a problem when using pynlpir. When I am trying to call the function ImportUserDict like this:
`import pynlpir`
`pynlpir.open()`
`pynlpir.nlpir.ImportUserDict('./data/dict.txt')`
Then there will be a type error for it like this:
`ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type`
I have found that maybe python2.7 can solve this problem but it is quite hard for me to convert the whole code to python2.7. So could you teach me how to solve this problem in python3.6 and pynlpir0.5.2?
Thanks!

**Comment by tsroten** [comment]
@jianghc724 Thanks for reporting this! I need to update the documentation. NLPIR requires bytes instead of unicode. So, here are two ways you can do it:
```python
pynlpir.nlpir.ImportUserDict(b'./data/dict.txt')
```
or
```python
pynlpir.nlpir.ImportUserDict('./data/dict.txt'.encode('utf-8'))
```

I'm not sure if NLPIR requires absolute filenames or not, so you might need to experiment with that.

**Comment by jianghc724** [comment]
Both of them solved my problem~
@tsroten Thanks!
