### ISSUE TITLE
pynlpir.nlpir.Init失败

### ISSUE THREAD

**Issue by Gladiator566** [tsroten/pynlpir#91]
您好，在使用pynlpir的ctype接口时，使用nlpir.Init(nlpir.PACKAGE_DIR, nlpir.UTF8_CODE)进行初始化，报错如下：TypeError: this function takes at least 3 arguments (2 given)
然后我改用nlpir.Init(nlpir.PACKAGE_DIR, nlpir.UTF8_CODE, '')进行初始化，但报错如下：
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
我的环境是Windows10，python3.6，请问正确的Init方法应该怎么写呢？
谢谢！

**Comment by disadone** [comment]
same problem,I should write it here
```
import pandas as pd
import pynlpir
import pynlpir.nlpir as nlpir

pynlpir.open(encoding='utf-8')
nlpir.Init(nlpir.PACKAGE_DIR,nlpir.UTF8_CODE,None)
nlpir.Init(nlpir.PACKAGE_DIR,nlpir.UTF8_CODE,'')
```

**Comment by tsroten** [comment]
You need to use bytes for the first argument to `Init` in Python 3. Here is an example: https://github.com/tsroten/pynlpir/blob/develop/pynlpir/__init__.py#L102

**Comment by Gladiator566** [comment]
Thanks a lot tsroten, I settle the problem by
```
nlpir.Init(str.encode(nlpir.PACKAGE_DIR), nlpir.UTF8_CODE, str.encode(''))
```
