### ISSUE TITLE
Cannot Init pynlpir.nlpir

### ISSUE THREAD

**Issue by disadone** [tsroten/pynlpir#93]
It seems  that nlpir has some problem in Ananconda/Spyder

> runfile('C:/Users/flumer/Documents/中文新闻文本/pynlpir_test/main.py', wdir='C:/Users/flumer/Documents/中文新闻文本/pynlpir_test')
> Traceback (most recent call last):
> 
>   File "<ipython-input-12-93df2cdba30c>", line 1, in <module>
>     runfile('C:/Users/flumer/Documents/中文新闻文本/pynlpir_test/main.py', wdir='C:/Users/flumer/Documents/中文新闻文本/pynlpir_test')
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/flumer/Documents/中文新闻文本/pynlpir_test/main.py", line 13, in <module>
>     nlpir.Init(nlpir.PACKAGE_DIR,nlpir.UTF8_CODE)
> 
> TypeError: this function takes at least 3 arguments (2 given)

**Comment by tsroten** [comment]
@disadone You need to pass in 3 arguments like the error message says. You're missing the `license_code` argument (try a blank bytes string).

But, rather than calling `Init()`, it's easier to do this:
```python
import pynlpir
pynlpir.open()
```
