### ISSUE TITLE
在Python中使用NLPIR的接口遇到問題

### ISSUE THREAD

**Issue by JinnyYu** [tsroten/pynlpir#95]
你好，爬了一下文，還是沒能解決問題，問題出現在213行
出現ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type的錯誤訊息
請問是因為我沒有改參數嗎?
環境是win10，python3.6
謝謝您
![q1023](https://user-images.githubusercontent.com/22863363/31873948-10384b22-b7f9-11e7-9602-81828e025354.JPG)

**Comment by tsroten** [comment]
你好，试一下用位元组：
```
Init(b'', ENCODING.UTF8_CODE, b'')
```
