### ISSUE TITLE
Having problem when trying to segment a sentence

### ISSUE THREAD

**Issue by stickjitb** [tsroten/pynlpir#97]
When I try to segment a sentence "〜refrain〜 The songs were inspired by &quot;EVANGELION&quot;", I will get the output "^|^|銆淾|^|refrain|^|^|銆淾|^|The|songs|were|inspired|by|&|quot|;|EVANGELION|" (| stands for the border of words)

If I delete the last word "EVANGELION", I will get the correct output "〜|refrain|〜| |The| |songs| |were| |inspired| |by| |&|quot|;|"

I know this program is mainly used for Chinese word segmentation, but I still wonder what causes this problem? It is quite interesting, isn't it?

**Comment by tsroten** [comment]
Yes it is! PyNLPIR doesn't do the segmentation, however. You'd have to check with the [ICTCLAS/NLPIR project](http://ictclas.nlpir.org/) that we use for this.
