### ISSUE TITLE
got a warning? part of speech not recognized: 'gjtgj'

### ISSUE THREAD

**Issue by cosmichut** [tsroten/pynlpir#98]
pynlpir.open()
>>> s='公司主营业务为地铁商业物业的租赁与运营管理服务。公司以整体租赁的方式取得轨道交通站点附属建筑物内商业物业的经营权 ，利用承租物业从事商铺出租和运营管理服务，公司对承租物业进行规划、定位、设计、改造，从满足商业业态经营需要和消费者需求等方面提升其商业价值空间，从而获得更优的租金收益。2015年和2014年公司经审计的营业收入分别为21,740,629.29元，550,498.50元， 主营业务收入占营业收入的比重为100%，自设立以来，公司主营业务未发生变化。'
>>> pynlpir.segment(s)
part of speech not recognized: 'gjtgj'
[('公司', 'noun'), ('主营业务', 'noun'), ('为', 'preposition'), ('地铁', None), ('商业', 'noun'), ('物业', 'noun'), ('的', 'particle'), ('租赁', 'verb'), ('与', 'conjunction'), ('运营', 'verb'), ('管理', 'verb'), ('服务', 'verb'), ('。', 'punctuation mark'), ('公司', 'noun'), ('以', 'preposition'), ('整体', 'noun'), ('租赁', 'verb'), ('的', 'particle'), ('方式', 'noun'), ('取得', 'verb'), ('轨道', 'noun'), ('交通', 'noun'), ('站点', 'noun'), ('附属', 'verb'), ('建筑物', 'noun'), ('内', 'noun of locality'), ('商业', 'noun'), ('物业', 'noun'), ('的', 'particle'), ('经营权', 'noun'), ('，', 'punctuation mark'), ('利用', 'verb'), ('承租', 'verb'), ('物业', 'noun'), ('从事', 'verb'), ('商铺', 'noun'), ('出租', 'verb'), ('和', 'conjunction'), ('运营', 'verb'), ('管理', 'verb'), ('服务', 'verb'), ('，', 'punctuation mark'), ('公司', 'noun'), ('对', 'preposition'), ('承租', 'verb'), ('物业', 'noun'), ('进行', 'verb'), ('规划', 'verb'), ('、', 'punctuation mark'), ('定位', 'noun'), ('、', 'punctuation mark'), ('设计', 'verb'), ('、', 'punctuation mark'), ('改造', 'verb'), ('，', 'punctuation mark'), ('从', 'preposition'), ('满足', 'verb'), ('商业', 'noun'), ('业态', 'noun'), ('经营', 'verb'), ('需要', 'noun'), ('和', 'conjunction'), ('消费者', 'noun'), ('需求', 'noun'), ('等', 'particle'), ('方面', 'noun'), ('提升', 'verb'), ('其', 'pronoun'), ('商业', 'noun'), ('价值', 'noun'), ('空间', 'noun'), ('，', 'punctuation mark'), ('从而', 'conjunction'), ('获得', 'verb'), ('更', 'adverb'), ('优', 'adjective'), ('的', 'particle'), ('租金', 'noun'), ('收益', 'noun'), ('。', 'punctuation mark'), ('2015年', 'time word'), ('和', 'conjunction'), ('2014年', 'time word'), ('公司', 'noun'), ('经', 'preposition'), ('审计', 'verb'), ('的', 'particle'), ('营业', 'verb'), ('收入', 'noun'), ('分别', 'adverb'), ('为', 'verb'), ('21', 'numeral'), (',', 'punctuation mark'), ('740', 'numeral'), (',', 'punctuation mark'), ('629.29', 'numeral'), ('元', 'classifier'), ('，', 'punctuation mark'), ('550', 'numeral'), (',', 'punctuation mark'), ('498.50', 'numeral'), ('元', 'classifier'), ('，', 'punctuation mark'), ('主营业务', 'noun'), ('收入', 'noun'), ('占', 'verb'), ('营业', 'verb'), ('收入', 'noun'), ('的', 'particle'), ('比重', 'noun'), ('为', 'preposition'), ('100%', 'numeral'), ('，', 'punctuation mark'), ('自', 'pronoun'), ('设立', 'verb'), ('以来', 'noun of locality'), ('，', 'punctuation mark'), ('公司', 'noun'), ('主营业务', 'noun'), ('未', 'adverb'), ('发生', 'verb'), ('变化', 'verb'), ('。', 'punctuation mark')]

**Comment by tsroten** [comment]
@cosmichut PyNLPIR is currently missing some of the recently-added part of speech tags:
https://github.com/tsroten/pynlpir/issues/82
