### ISSUE TITLE
License appears to have expired?

### ISSUE THREAD

**Issue by ZoeShaw101** [tsroten/pynlpir#99]
Hi, I'm trying to use the python wrapper, but when running `pynlpir.open()`, the error raised:
 
`
pynlpir.LicenseError: Your license appears to have expired. Try running "pynlpir update".
`
Actually I don't  known where to run `pynlpir update` ?  In the console ? terminal?

I'm using python2.7, on OSX. 
Thanks a lot!

**Comment by tsroten** [comment]
Hi! Yes, NLPIR requires a license, so I wrote a command-line application to download and install the most recent license so that PyNLPIR is easier to use.

In your terminal simply run "pynlpir update" and it should fetch and install the license.

**Comment by terry2tan** [comment]
@tsroten Hi, I ran "pynlpir update" in the terminal  and it told me "License updated", but when i turned to the code and run the code again, it raised the error:
RuntimeError: NLPIR function 'NLPIR_Init' failed.

my OS : mac Sierra 10.12
python version:  2.7

**Comment by terry2tan** [comment]
@tsroten I think I found the problem, I checked the log file in the Data folder, it told me "Other thread is under initialization", so i closed all the ipython notebook and restarted the jupyter notebook, it worked!
